name-template: 'Draft for 8.0'
tag-template: 'Draft for 8.0'
filter-by-commitish: true
commitish: develop
version-template: 'Draft for 8.0'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
  - title: '🐛 Bug Fixes'
    labels:
      - 'bug'
template: |
  ## What’s Changed
  $CHANGES
